name: inference-pipeline

# on:
#   # inference pipeline will run when the feature pipeline is completed
#   workflow_run:
#     workflows: ["feature-pipeline"]
#     types:
#       - completed

#   workflow_dispatch:


# Running right after the feature pipeline is problematic because there is a lag in Hopsworks being updated, so I 
# run this inference pipeline 30 minutes after feature pipeline to be sure that new data will be pulled
on:
  schedule:
    # Run at 1:00 UTC, which is 9:00PM EST
    - cron: '0 1 * * *'
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.9
jobs:
  feature_pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_inference_pipeline.txt

    - name: Execute Python workflows from bash script
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
      run: jupyter nbconvert --to notebook --execute notebooks/09_ohlc_inference_pipeline.ipynb
